- name: Mount tmpfs partition in memory
  mount:
    name: /var/cache/knot-resolver
    src: tmpfs
    fstype: tmpfs
    opts: "rw,size={{ dns_cache_size }}M,uid=knot-resolver,gid=knot-resolver,nosuid,nodev,noexec,mode=0700"
    state: mounted