- name: Install certbot
  apt:
    pkg:
      - certbot
    update_cache: yes
    state: present
  become: yes

- name: Obtain certificate
  shell:
    cmd: "certbot certonly --standalone --agree-tos -n -m {{ dns_letsencrypt_email }} -d {{ dns_letsencrypt_fqdn }}"
  notify: restart_knot
  become: yes

- name: Copy certificates to desired location
  copy:
    src: "/etc/letsencrypt/live/{{ dns_letsencrypt_fqdn }}/{{ item }}"
    dest: "{{ dns_tls_cert_key_directory }}/{{ item }}"
    remote_src: yes
    owner: knot-resolver
    group: knot-resolver
  loop:
    - "privkey.pem"
    - "fullchain.pem"
  become: yes