- name: Install certbot
  apt:
    pkg:
      - certbot
    update_cache: yes
    state: present
  become: yes

- name: Create hook directory
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    owner: "root"
    group: "root"
    mode: 0740
  become: yes

- name: Copy hook file to server
  template:
    src: 10_copy_certs_and_restart_knot.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/10_copy_certs_and_restart_knot
    mode: '740'
    owner: "root"
    group: "root"
  become: yes

- name: Obtain certificate
  shell:
    cmd: "certbot certonly --standalone --agree-tos -n -m {{ dns_letsencrypt_email }} -d {{ dns_letsencrypt_fqdn }}"
  notify: restart_knot
  become: yes

- name: Copy certificates to desired location
  copy:
    src: "/etc/letsencrypt/live/{{ dns_letsencrypt_fqdn }}/{{ item }}"
    dest: "{{ dns_tls_cert_key_directory }}/{{ item }}"
    remote_src: yes
    owner: knot-resolver
    group: knot-resolver
  loop:
    - "privkey.pem"
    - "fullchain.pem"
  become: yes